<a href="https://colab.research.google.com/github/Josephmd2k4/MedicineMidterm/blob/main/midterm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
from sklearn.datasets import load_digits
import numpy as np
from sklearn.linear_model import Perceptron
from matplotlib.colors import ListedColormap
import matplotlib.pyplot as plt
import matplotlib
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

Run code that all machine learning methods need, getting the data and splitting it into a training set and a testing set. Then standardizing the data.

In [43]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X, y = load_digits(return_X_y= True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=5, stratify=y)
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

Logistic Regression code

In [44]:
from sklearn.linear_model import LogisticRegression
#create logistic regression object with sklearn, fit the data into it
lr = LogisticRegression(C=10.0, solver='lbfgs', multi_class='multinomial')
lr.fit(X_train_std, y_train)

#predict labels based on the fitted data
y_pred = lr.predict(X_test_std)

#compute accuracy and amount missed
accuracy = accuracy_score(y_test, y_pred)
missed = (y_test != y_pred).sum()
print(f'Misclassified examples: {missed}')
print(f"Accuracy: {100* accuracy:.2f}%")
print(f"          {y_test.size - missed}/{y_test.size}")

#print classification report and confusion matrix
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))



Misclassified examples: 14
Accuracy: 97.41%
          526/540
Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        54
           1       0.96      0.98      0.97        55
           2       0.96      1.00      0.98        53
           3       1.00      0.96      0.98        55
           4       1.00      0.98      0.99        54
           5       1.00      0.95      0.97        55
           6       0.98      0.98      0.98        54
           7       0.98      0.98      0.98        54
           8       0.94      0.94      0.94        52
           9       0.93      0.96      0.95        54

    accuracy                           0.97       540
   macro avg       0.97      0.97      0.97       540
weighted avg       0.97      0.97      0.97       540

Confusion Matrix:
[[54  0  0  0  0  0  0  0  0  0]
 [ 0 54  0  0  0  0  0  0  1  0]
 [ 0  0 53  0  0  0  0  0  0  0]
 [ 0  0  1 53  0  0  0  0  1  0]
 [ 0  

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Multi-Layer Perceptron Code

In [37]:
from sklearn.neural_network import MLPClassifier


mlp = MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=1000, random_state=42)
mlp.fit(X_train_std, y_train)


y_pred = mlp.predict(X_test_std)


accuracy = accuracy_score(y_test, y_pred)
missed = (y_test != y_pred).sum()
print(f'Misclassified examples: {missed}')
print(f"Accuracy: {100* accuracy:.2f}%")
print(f"          {y_test.size - missed}/{y_test.size}")

print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Misclassified examples: 15
Accuracy: 97.22%
          525/540
Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        54
           1       0.95      1.00      0.97        55
           2       0.96      0.98      0.97        53
           3       0.98      0.95      0.96        55
           4       1.00      1.00      1.00        54
           5       1.00      0.93      0.96        55
           6       0.98      0.96      0.97        54
           7       0.96      0.98      0.97        54
           8       0.96      0.94      0.95        52
           9       0.95      0.98      0.96        54

    accuracy                           0.97       540
   macro avg       0.97      0.97      0.97       540
weighted avg       0.97      0.97      0.97       540

Confusion Matrix:
[[54  0  0  0  0  0  0  0  0  0]
 [ 0 55  0  0  0  0  0  0  0  0]
 [ 0  0 52  0  0  0  0  1  0  0]
 [ 0  0  1 52  0  0  0  1  1  0]
 [ 0  

K nearest Neighbor Code

In [38]:
from sklearn.neighbors import KNeighborsClassifier

knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_train, y_train)


y_pred = knn_classifier.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
missed = (y_test != y_pred).sum()
print(f'Misclassified examples: {missed}')
print(f"Accuracy: {100* accuracy:.2f}%")
print(f"          {y_test.size - missed}/{y_test.size}")

print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Misclassified examples: 10
Accuracy: 98.15%
          530/540
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        54
           1       0.95      1.00      0.97        55
           2       1.00      0.98      0.99        53
           3       1.00      0.96      0.98        55
           4       1.00      1.00      1.00        54
           5       1.00      0.96      0.98        55
           6       0.98      1.00      0.99        54
           7       0.95      1.00      0.97        54
           8       0.98      0.94      0.96        52
           9       0.96      0.96      0.96        54

    accuracy                           0.98       540
   macro avg       0.98      0.98      0.98       540
weighted avg       0.98      0.98      0.98       540

Confusion Matrix:
[[54  0  0  0  0  0  0  0  0  0]
 [ 0 55  0  0  0  0  0  0  0  0]
 [ 0  0 52  0  0  0  0  1  0  0]
 [ 0  0  0 53  0  0  0  2  0  0]
 [ 0  

SVM Code

In [39]:
from sklearn.svm import SVC

svm_classifier = SVC(kernel='linear')
svm_classifier.fit(X_train_std, y_train)


y_pred = svm_classifier.predict(X_test_std)


accuracy = accuracy_score(y_test, y_pred)
missed = (y_test != y_pred).sum()
print(f'Misclassified examples: {missed}')
print(f"Accuracy: {100* accuracy:.2f}%")
print(f"          {y_test.size - missed}/{y_test.size}")

print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Misclassified examples: 12
Accuracy: 97.78%
          528/540
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        54
           1       0.95      1.00      0.97        55
           2       0.96      1.00      0.98        53
           3       0.98      0.96      0.97        55
           4       1.00      1.00      1.00        54
           5       1.00      0.98      0.99        55
           6       1.00      0.98      0.99        54
           7       0.98      0.98      0.98        54
           8       0.94      0.94      0.94        52
           9       0.96      0.93      0.94        54

    accuracy                           0.98       540
   macro avg       0.98      0.98      0.98       540
weighted avg       0.98      0.98      0.98       540

Confusion Matrix:
[[54  0  0  0  0  0  0  0  0  0]
 [ 0 55  0  0  0  0  0  0  0  0]
 [ 0  0 53  0  0  0  0  0  0  0]
 [ 0  0  1 53  0  0  0  0  1  0]
 [ 0  